# Generated by Django 5.2 on 2025-12-31 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('primary_language', models.CharField(max_length=50)),
                ('other_languages', models.CharField(blank=True, help_text='Comma-separated', max_length=200)),
                ('best_seasons', models.CharField(help_text="e.g., 'Spring,autumn'", max_length=200)),
                ('cost_level', models.CharField(choices=[('budget', 'Budget-Friendly'), ('moderate', 'Moderate'), ('luxury', 'Luxury')], max_length=20)),
                ('avg_hotel_cost_per_night', models.DecimalField(decimal_places=2, max_digits=6)),
                ('avg_meal_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField()),
                ('highlights', models.TextField(help_text='What makes this city special')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('museum_art', 'Art Museum'), ('museum_history', 'History Museum'), ('museum_science', 'Science Museum'), ('architecture', 'Architecture & Monuments'), ('nature', 'Nature & Parks'), ('beach', 'Beach'), ('cultural', 'Cultural Venue'), ('food', 'Food & Markets'), ('nightlife', 'Nightlife'), ('shopping', 'Shopping'), ('religious', 'Religious Site'), ('viewpoint', 'Viewpoint')], max_length=50)),
                ('description', models.TextField()),
                ('is_free', models.BooleanField(default=False)),
                ('entry_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('importance', models.IntegerField(choices=[(1, 'Must See'), (2, 'Highly Recommended'), (3, 'Worth Visiting'), (4, 'Optional')], default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='destinations.city')),
            ],
            options={
                'ordering': ['importance', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('festival', 'Festival'), ('market', 'Market'), ('concert', 'Concert/Music'), ('sports', 'Sports Event'), ('cultural', 'Cultural Event'), ('food', 'Food & Wine Event'), ('seasonal', 'Seasonal Event')], max_length=50)),
                ('description', models.TextField()),
                ('season', models.CharField(choices=[('winter', 'Winter'), ('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn'), ('year_round', 'Year Round')], max_length=20)),
                ('specific_months', models.CharField(blank=True, help_text="e.g., 'December', 'June-August'", max_length=100)),
                ('is_free', models.BooleanField(default=False)),
                ('typical_cost', models.CharField(blank=True, help_text="e.g., '€20-50'", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='destinations.city')),
            ],
            options={
                'ordering': ['season', 'name'],
            },
        ),
    ]
