# Generated by Django 5.2 on 2025-12-31 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='is_unesco_heritage',
            field=models.BooleanField(default=False, help_text='Has UNESCO World Heritage Site(s)'),
        ),
        migrations.AddField(
            model_name='city',
            name='unesco_sites',
            field=models.TextField(blank=True, help_text='List UNESCO World Heritage sites in this city'),
        ),
    ]
