# Generated by Django 5.2 on 2026-01-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_city_is_unesco_heritage_city_unesco_sites'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='hero_image_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
