# Generated by Django 5.2 on 2026-05-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_city_hero_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='primary_categories',
            field=models.CharField(blank=True, help_text='Comma-separated: art,food,history', max_length=200),
        ),
    ]
