# Generated by Django 5.2 on 2025-12-31 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name or persona description', max_length=100)),
                ('is_simulated', models.BooleanField(default=False, help_text='Is this a test persona?')),
                ('bio', models.TextField(blank=True, help_text='Rich persona backstory for portfolio demo')),
                ('age', models.IntegerField(blank=True, help_text='Persona age', null=True)),
                ('occupation', models.CharField(blank=True, help_text='Persona occupation', max_length=100)),
                ('budget_preference', models.CharField(choices=[('budget', 'Budget-Friendly (€50-100/day)'), ('moderate', 'Moderate (€100-200/day)'), ('luxury', 'Luxury (€200+/day)')], max_length=20)),
                ('preferred_trip_length', models.CharField(choices=[('2-3', '2-3 days'), ('3-4', '3-4 days'), ('5-7', '5-7 days'), ('7+', '7+ days')], max_length=10)),
                ('languages', models.CharField(help_text="Comma-separated, e.g., 'English,Spanish'", max_length=200)),
                ('interests', models.TextField(help_text='Comma-separated interests')),
                ('preferred_season', models.CharField(choices=[('winter', 'Winter (Dec-Feb)'), ('spring', 'Spring (Mar-May)'), ('summer', 'Summer (Jun-Aug)'), ('autumn', 'Autumn (Sep-Nov)'), ('flexible', 'Flexible')], default='flexible', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional preferences or persona description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
