# Generated by Django 5.2 on 2025-12-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='departure_city',
            field=models.CharField(blank=True, help_text='Where are you traveling from?', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='departure_country',
            field=models.CharField(blank=True, help_text='Departure country', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='transport_preference',
            field=models.CharField(choices=[('no_preference', 'No Preference'), ('prefer_train', 'Prefer Train'), ('prefer_flight', 'Prefer Flight'), ('train_only', 'Train Only (Avoid Flying)'), ('bus_ok', 'Open to Bus/Coach')], default='no_preference', help_text='Preferred mode of transport', max_length=20),
        ),
    ]
