# Generated by Django 5.2 on 2025-12-31 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenceSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.CharField(max_length=20)),
                ('trip_length', models.CharField(max_length=10)),
                ('languages', models.CharField(max_length=200)),
                ('interests', models.TextField()),
                ('preferred_season', models.CharField(max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='users.userprofile')),
            ],
            options={
                'verbose_name': 'Preference Submission',
                'verbose_name_plural': 'Preference Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
