# Generated by Django 5.2 on 2025-12-31 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, help_text='Total score (0-100)', max_digits=5)),
                ('weighted_score', models.DecimalField(decimal_places=2, help_text='Algorithm score', max_digits=5)),
                ('ai_score', models.DecimalField(blank=True, decimal_places=2, help_text='Gemini API score', max_digits=5, null=True)),
                ('match_reasoning', models.TextField(blank=True, help_text='Why this city matches (from Gemini)')),
                ('personalized_description', models.TextField(blank=True, help_text='Custom description for user')),
                ('rank', models.IntegerField(help_text='Position in results (1=best match)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destinations.city')),
                ('preference_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='preferences.preferencesubmission')),
            ],
            options={
                'ordering': ['preference_submission', 'rank'],
                'unique_together': {('preference_submission', 'city')},
            },
        ),
    ]
